#
# GNUmakefile - Generated by ProjectCenter
# Written by Philippe C.D. Robert <phr@3dkit.org>
# GormApplication project type contibuted by Pierre-Yves Rivaille <pyrivail@ens-lyon.fr>
#
# NOTE: Do NOT change this file -- ProjectCenter maintains it!
#
# Put all of your customisations in GNUmakefile.preamble and
# GNUmakefile.postamble
#

include $(GNUSTEP_MAKEFILES)/common.make
#

# Subprojects
#

#
# Main application
#

PACKAGE_NAME=EasyDiff
APP_NAME=EasyDiff
GNUSTEP_INSTALLATION_DIR=$(GNUSTEP_LOCAL_ROOT)/
EasyDiff_MAIN_MODEL_FILE=EasyDiff.gorm
EasyDiff_APPLICATION_ICON=
#

# Additional libraries
#

ADDITIONAL_GUI_LIBS += 

#

# Resource files
#

EasyDiff_RESOURCE_FILES= \
EasyDiff.gorm \
DiffWindow.gorm \
EasyDiffInfo.plist 

#

# Header files
#

EasyDiff_HEADERS= \
AppController.h \
DiffTextView.h \
DiffMiddleView.h \
DiffView.h \
DiffWindowController.h 

#

# Class files
#

EasyDiff_OBJC_FILES= \
main.m \
AppController.m \
DiffTextView.m \
DiffMiddleView.m \
DiffView.m \
DiffWrapper.m \
DiffWindowController.m \
DiffScroller.m

#

# C files
#

EasyDiff_C_FILES= 

-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
