#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.4.1
PACKAGE_NAME = EasyDiff
APP_NAME = EasyDiff
EasyDiff_APPLICATION_ICON = 
SVN_MODULE_NAME = easydiff
SVN_BASE_URL = svn+ssh://svn.gna.org/svn/gnustep/apps


#
# Resource files
#
EasyDiff_RESOURCE_FILES = \
Resources/main.gorm \
Resources/window.gorm 


#
# Header files
#
EasyDiff_HEADER_FILES = \
AppController.h \
DiffTextView.h \
DiffMiddleView.h \
DiffView.h \
DiffWrapper.h \
DiffWindowController.h \
DiffScroller.h\
DiffFileChooser.h \
FileIconView.h

#
# Class files
#
EasyDiff_OBJC_FILES = \
main.m \
AppController.m \
DiffTextView.m \
DiffMiddleView.m \
DiffView.m \
DiffWrapper.m \
DiffWindowController.m \
DiffScroller.m \
DiffFileChooser.m \
FileIconView.m

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
